# Generated by Django 3.0.2 on 2020-01-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200122_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
