# Generated by Django 3.0.2 on 2020-01-24 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200123_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='groups/'),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=datetime.datetime(2020, 1, 24, 8, 16, 11, 862653, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
